### PR TITLE
Comms functions for sharepoint and teams 

### PR DESCRIPTION
**Pull request by nish-kishore**
Didn't see a lot of functionality for reading from sharepoint but can do that as well.

### CODE REVIEW

**Comment by nish-kishore** [comment]
Have requested permissions to send direct chats but don't have that yet

**Review by Heaghneyn — COMMENTED** [review]
upload_to_sharepoint doesn't connect to site

Error: Site 'CGH-GID-PEB-SIR' not found

**Review by Heaghneyn — CHANGES_REQUESTED** [review]
upload_to_sharepoint is generating this error:
Error: Site 'CGH-GID-PEB-SIR' not found

code ran: upload_to_sharepoint("C:/Users/uic3/Desktop/gitrepos/sirfunctions/README.md", sp_folder = "General/SIA Impact Reports/")

**Comment by nish-kishore** [comment]
Commit 2e21d1e has been tested by both @nish-kishore and @Heaghneyn to verify functionality. For the sharepoint function, static references have been attached to a URL rather than the site name.

**Review by Heaghneyn — APPROVED** [review]

**Pull request merged**
